name: Deploy Static Assets to S3

on:
  push:
    branches:
      - main
    paths:
      - 'static/**'
  workflow_dispatch:

jobs:
  deploy-static:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Find changed static files
        run: |
          git fetch origin main
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- static/ > all.txt
          # filter out any empties and write back only real paths
          grep -v '^$' all.txt > changed.txt || true

      - name: Sync & upload only those files
        run: |
          while read FILE; do
            if [ -f "$FILE" ]; then
              aws s3 cp "$FILE" "s3://taptupo.com/${FILE#static/}"
            else
              echo "File $FILE does not exist. Skipping..."
            fi
          done < changed.txt      

      - name: Invalidate only those files
        run: |
          PATHS=()
          while read FILE; do
            PATHS+=( "/${FILE#static/}" )
          done < changed.txt

          if [ ${#PATHS[@]} -eq 0 ]; then
            echo "No files to invalidate. Skipping CloudFront invalidation."
          else
            aws cloudfront create-invalidation \
              --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
              --paths "${PATHS[@]}"
          fi

      - name: Done
        run: echo "Static deploy complete."
