name: Deploy Go Lambda Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build & Zip Lambda
        run: |
          cd lambda

          # fetch dependencies (from lambda/go.mod)
          go mod download

          # compile for Linux (Amazon Linux)
          GOOS=linux GOARCH=amd64 \
            go build -o main exchange_handler.go

          # zip into repo-root/deployment.zip
          zip ../deployment.zip main

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.1
        with:
          access_key_id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region:            us-east-1       
          zip_file:          deployment.zip