name: Deploy Go Lambda Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build & Zip Lambda
        run: |
          cd lambda
          go mod download
          GOOS=linux GOARCH=amd64 go build -o main exchange_handler.go
          zip ../deployment.zip main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Create Lambda if missing
        run: |
          if ! aws lambda get-function --function-name exchangeHandler >/dev/null 2>&1; then
            aws lambda create-function \
              --function-name exchangeHandler \
              --runtime go1.x \
              --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/lambda_exec_role \
              --handler main \
              --zip-file fileb://deployment.zip
          fi

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.1
        with:
          access_key_id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region:            us-east-1
          function_name:     exchangeHandler
          zip_file:          deployment.zip
