name: Deploy Changed Go Lambda Functions

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'
  pull_request:
    paths:
      - 'lambda/**'

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Find changed Go lambda functions
        id: find_functions
        run: |
          echo "Comparing ${GITHUB_EVENT_BEFORE} → ${GITHUB_SHA}"
          git fetch --no-tags origin main

          # Extract only the directory name under lambda/
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'lambda/**/*.go' \
            | awk -F/ '{print $2}' \
            | sort -u \
            | tr '\n' ' ')
          echo "functions=$CHANGED" >> $GITHUB_ENV
          echo "Changed functions: $CHANGED"

      - name: Build, zip, and deploy changed lambdas
        if: env.functions != ''
        run: |
          set -euo pipefail
          trap 'echo "❌ Error on line $LINENO"; exit 1' ERR

          for fn in $functions; do
            echo "=== Deploying lambda/$fn ==="
            pushd "lambda/$fn"

            echo "→ Tidying module (go.mod & go.sum)"
            export GO111MODULE=on
            go mod tidy

            echo "→ Downloading modules"
            go mod download

            echo "→ Building $fn"
            GOOS=linux GOARCH=amd64 go build -mod=readonly -o bootstrap *.go

            echo "→ Zipping $fn"
            zip -q "${fn}.zip" bootstrap

            echo "→ Publishing $fn to Lambda"
            if ! aws lambda get-function --function-name "$fn" >/dev/null 2>&1; then
              aws lambda create-function \
                --function-name "$fn" \
                --runtime provided.al2 \
                --role arn:aws:iam::${ACCOUNT_ID}:role/lambda_exec_role \
                --handler bootstrap \
                --zip-file fileb://"${fn}.zip"
            else
              aws lambda update-function-code \
                --function-name "$fn" \
                --zip-file fileb://"${fn}.zip"
            fi

            popd
          done
