name: Deploy Changed Go Lambda Functions

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'
  pull_request:
    paths:
      - 'lambda/**'

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Enforce static, linux/amd64 build everywhere in this job
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: "0"

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Find changed Go lambda functions
        id: find_functions
        run: |
          git fetch --no-tags origin main
          functions=$(git diff --name-only origin/main $GITHUB_SHA \
            | grep '^lambda/' \
            | cut -f2 -d/ \
            | uniq)
          echo "Functions to deploy: $functions"
          echo "::set-output name=functions::$functions"

      - name: Deploy functions
        run: |
          for fn in ${{ steps.find_functions.outputs.functions }}; do
            echo "=== Deploying lambda/$fn ==="
            pushd "lambda/$fn"

            # Modules
            if [ -f go.mod ]; then
              go mod tidy
              go mod download
            else
              go mod init "$fn"
              go mod tidy
            fi

            # Build statically
            echo "→ Building static bootstrap"
            go build -mod=readonly -ldflags="-s -w" -o bootstrap *.go

            # Verify static linking
            echo "→ Verifying bootstrap is static"
            file bootstrap
            if ldd bootstrap 2>&1 | grep -q 'not a dynamic executable'; then
              echo "✅ bootstrap is fully static"
            else
              echo "❌ ERROR: bootstrap is dynamically linked!" >&2
              ldd bootstrap
              exit 1
            fi

            # Package & publish
            zip -q "${fn}.zip" bootstrap
            ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/lambda_exec_role"

            if ! aws lambda get-function --function-name "$fn" >/dev/null 2>&1; then
              aws lambda create-function \
                --function-name "$fn" \
                --runtime provided.al2 \
                --role "$ROLE_ARN" \
                --handler bootstrap \
                --zip-file fileb://"${fn}.zip"
            else
              aws lambda update-function-code \
                --function-name "$fn" \
                --zip-file fileb://"${fn}.zip"
            fi

            popd
          done
