name: Terraform Deploy Infrastructure

on:
  push:
    branches: [main]

jobs:
  terraform-deploy:
    name: Deploy Infra + Upload Static Content
    runs-on: ubuntu-latest

    env:
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      TF_VAR_domain: ${{ secrets.DOMAIN_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      working-directory: .
      run: terraform init

    - name: Terraform Plan
      working-directory: .
      run: terraform plan -var="s3_bucket_name=$S3_BUCKET_NAME"

    - name: Terraform Apply
      working-directory: .
      run: terraform apply -auto-approve -var="s3_bucket_name=$S3_BUCKET_NAME"

    - name: Upload Static Files to S3
      run: |
        aws s3 sync ./static-site s3://$S3_BUCKET_NAME --delete --acl public-read
