# .github/workflows/deploy-europeana-handler.yml
name: Deploy Europeana Handler Lambda

on:
  push:
    paths:
      - 'lambda/europeana_handler/**'
  workflow_dispatch:

jobs:
  deploy-europeana-handler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Normalize go.mod version
        run: |
          cd lambda/europeana_handler
          # Replace any 3-part go directive like "go 1.22.2" with "go 1.22"
          sed -i 's/^go [0-9]\+\.[0-9]\+\.[0-9]\+$/go 1.22/' go.mod

      - name: Build Lambda bootstrap
        run: |
          cd lambda/europeana_handler
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
            go build -o bootstrap europeana_handler.go
          zip -j function.zip bootstrap

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name europeana-lambda \
            --zip-file fileb://lambda/europeana_handler/function.zip
